### Working with Tensorflow Datasets

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

2024-02-12 10:29:06.719488: W tensorflow/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata.google.internal".


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /Users/medhaniesolomon/tensorflow_datasets/fashion_mnist/3.0.1.incompleteEEPMLT/fashion_mnist-train.…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /Users/medhaniesolomon/tensorflow_datasets/fashion_mnist/3.0.1.incompleteEEPMLT/fashion_mnist-test.t…

Dataset fashion_mnist downloaded and prepared to /Users/medhaniesolomon/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
train
test


In [2]:
# load splits into dataset with real data
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>


In [4]:
# get first record
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2024-02-12 10:51:25.585781: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int64 and shape [1]
	 [[{{node Placeholder/_3}}]]
2024-02-12 10:51:25.586316: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [1]
	 [[{{node Placeholder/_4}}]]
2024-02-12 10:51:25.628419: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline si

In [5]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
info

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/Users/medhaniesolomon/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,


In [6]:
# use tfds with keras
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split=['train', 'test'],
                                                                                         batch_size=-1, as_supervised=True))

training_images = training_images / 255.0
test_images = test_images / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [7]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 790us/step - loss: 0.5270 - accuracy: 0.8138
Epoch 2/5
1875/1875 [==============================] - 1s 716us/step - loss: 0.3970 - accuracy: 0.8558
Epoch 3/5
1875/1875 [==============================] - 1s 797us/step - loss: 0.3626 - accuracy: 0.8669
Epoch 4/5
1875/1875 [==============================] - 1s 687us/step - loss: 0.3423 - accuracy: 0.8731
Epoch 5/5
1875/1875 [==============================] - 1s 721us/step - loss: 0.3271 - accuracy: 0.8799


In [9]:
# horse or human data
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1027 [00:00<?, ? examples/s]

Shuffling /Users/medhaniesolomon/tensorflow_datasets/horses_or_humans/3.0.0.incompleteXL21OK/horses_or_humans-…

Generating test examples...:   0%|          | 0/256 [00:00<?, ? examples/s]

Shuffling /Users/medhaniesolomon/tensorflow_datasets/horses_or_humans/3.0.0.incompleteXL21OK/horses_or_humans-…

Dataset horses_or_humans downloaded and prepared to /Users/medhaniesolomon/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.


In [10]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu',
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu',
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu',
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu',
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation="relu"),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [11]:
model.compile(optimizer='Adam', loss='binary_crossentropy',
              metrics=['accuracy'])

In [12]:
history = model.fit(train_batches, epochs=10)

Epoch 1/10


2024-02-12 17:15:54.606121: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [2]
	 [[{{node Placeholder/_4}}]]
2024-02-12 17:15:54.606980: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int64 and shape [2]
	 [[{{node Placeholder/_3}}]]


103/103 [==============================] - 14s 129ms/step - loss: 10.1726 - accuracy: 0.8267
Epoch 2/10
103/103 [==============================] - 12s 114ms/step - loss: 0.1189 - accuracy: 0.9503
Epoch 3/10
103/103 [==============================] - 12s 113ms/step - loss: 0.0485 - accuracy: 0.9786
Epoch 4/10
103/103 [==============================] - 12s 117ms/step - loss: 0.0281 - accuracy: 0.9912
Epoch 5/10
103/103 [==============================] - 15s 148ms/step - loss: 0.1510 - accuracy: 0.9649
Epoch 6/10
103/103 [==============================] - 16s 152ms/step - loss: 0.0184 - accuracy: 0.9932
Epoch 7/10
103/103 [==============================] - 14s 135ms/step - loss: 0.0038 - accuracy: 0.9990
Epoch 8/10
103/103 [==============================] - 14s 136ms/step - loss: 0.0031 - accuracy: 0.9990
Epoch 9/10
103/103 [==============================] - 15s 145ms/step - loss: 5.2055e-04 - accuracy: 1.0000
Epoch 10/10
103/103 [==============================] - 15s 146ms/step - loss: 1

In [13]:
# validation data
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)
validation_batches = val_data.batch(32)
history = model.fit(train_batches, epochs=10,
validation_data = validation_batches, validation_steps=1)

Epoch 1/10
103/103 [==============================] - ETA: 0s - loss: 1.1527e-04 - accuracy: 1.0000

2024-02-12 17:18:54.260886: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_4' with dtype int64 and shape [1]
	 [[{{node Placeholder/_4}}]]
2024-02-12 17:18:54.261677: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_3' with dtype int64 and shape [1]
	 [[{{node Placeholder/_3}}]]


103/103 [==============================] - 14s 137ms/step - loss: 1.1527e-04 - accuracy: 1.0000 - val_loss: 4.2308 - val_accuracy: 0.7500
Epoch 2/10
  1/103 [..............................] - ETA: 17s - loss: 8.8207e-06 - accuracy: 1.0000

2024-02-12 17:18:54.814671: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 14s 133ms/step - loss: 8.5516e-05 - accuracy: 1.0000 - val_loss: 4.2565 - val_accuracy: 0.7500
Epoch 3/10
  1/103 [..............................] - ETA: 12s - loss: 7.3200e-06 - accuracy: 1.0000

2024-02-12 17:19:08.560259: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 13s 128ms/step - loss: 6.5667e-05 - accuracy: 1.0000 - val_loss: 4.2757 - val_accuracy: 0.7500
Epoch 4/10
  1/103 [..............................] - ETA: 12s - loss: 1.2415e-05 - accuracy: 1.0000

2024-02-12 17:19:21.740591: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 14s 132ms/step - loss: 5.1425e-05 - accuracy: 1.0000 - val_loss: 4.3097 - val_accuracy: 0.7500
Epoch 5/10
  1/103 [..............................] - ETA: 19s - loss: 2.0696e-04 - accuracy: 1.0000

2024-02-12 17:19:35.342867: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 13s 128ms/step - loss: 4.1419e-05 - accuracy: 1.0000 - val_loss: 4.3422 - val_accuracy: 0.7500
Epoch 6/10
  1/103 [..............................] - ETA: 13s - loss: 8.4561e-06 - accuracy: 1.0000

2024-02-12 17:19:48.645631: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 13s 129ms/step - loss: 3.3306e-05 - accuracy: 1.0000 - val_loss: 4.3738 - val_accuracy: 0.7500
Epoch 7/10
  1/103 [..............................] - ETA: 12s - loss: 4.3177e-06 - accuracy: 1.0000

2024-02-12 17:20:01.892491: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 15s 147ms/step - loss: 2.7075e-05 - accuracy: 1.0000 - val_loss: 4.4045 - val_accuracy: 0.7500
Epoch 8/10
  1/103 [..............................] - ETA: 12s - loss: 1.3333e-06 - accuracy: 1.0000

2024-02-12 17:20:17.009501: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 13s 128ms/step - loss: 2.2641e-05 - accuracy: 1.0000 - val_loss: 4.4520 - val_accuracy: 0.7500
Epoch 9/10
  1/103 [..............................] - ETA: 13s - loss: 6.0383e-06 - accuracy: 1.0000

2024-02-12 17:20:30.212988: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 14s 133ms/step - loss: 1.8837e-05 - accuracy: 1.0000 - val_loss: 4.4922 - val_accuracy: 0.7500
Epoch 10/10
  1/103 [..............................] - ETA: 13s - loss: 3.9390e-07 - accuracy: 1.0000

2024-02-12 17:20:43.954200: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


103/103 [==============================] - 14s 136ms/step - loss: 1.5614e-05 - accuracy: 1.0000 - val_loss: 4.5323 - val_accuracy: 0.7500


2024-02-12 17:20:57.921956: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [ ]:
# augmentation
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = image/255
    image = tf.image.random_flip_left_right(image)
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)